### ISSUE TITLE
About img's lesion id

### ISSUE THREAD

**Issue by steven-chow** [ngessert/isic2018#1]
Hi!
Thanks for opening your  code.  It is really a big help for other researchers.

In you paper, you mentioned that "All images were separated based on lesion affiliation,
i.e., we made sure that images from the same lesion cannot occur both in a training and validation split."

I know this strategy do make a difference when training, but i  don't know how to get the  lesion affiliation.

**Comment by ngessert** [comment]
Hi, you can find the info here: https://forum.isic-archive.com/t/task-3-supplemental-information/430

**Comment by ZDstandup** [comment]
Wow, thanks for your help. I will go on following your research.
