### ISSUE TITLE
No module named pretrainedmodels

### ISSUE THREAD

**Issue by allaedding** [ngessert/isic2018#4]
hello sir,
when trying to run your code, for example:
`python train.py example ISIC.example_senet_5foldcv`

this error appear: 

`Traceback (most recent call last):
  File "train.py", line 38, in <module>
    import models
  File "/content/models.py", line 8, in <module>
    import pretrainedmodels
ModuleNotFoundError: No module named 'pretrainedmodels'`

**Comment by ChauncyHe** [comment]
Hello,
I have the same error now. Have you solved this problem?

**Comment by ngessert** [comment]
You can install it using: pip install pretrainedmodels
You can find the package here: https://github.com/Cadene/pretrained-models.pytorch

**Comment by ChauncyHe** [comment]
It works. Thank you very much.


| |
hcxzct
|
|
hcxzct@163.com
|
签名由网易邮箱大师定制
On 8/8/2019 21:29，Nils Gessert<notifications@github.com> wrote：

You can install it using: pip install pretrainedmodels
You can find the package here: https://github.com/Cadene/pretrained-models.pytorch
